rrll/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView
from django.urls import include, path, re_path

# from rrll import settings

from . import views

urlpatterns = [
    path("volunteers/", include("volunteers.urls")),
    path("boardmembers/", include("boardmembers.urls")),
    path("", views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("schedule/", views.schedule, name="schedule"),
    path("safety/", views.safety, name="safety"),
    path("news/", views.news, name="news"),
    path("registration/", views.registration, name="registration"),
    path('admin/', admin.site.urls),
    re_path(r'^favicon\.ico$',RedirectView.as_view(url='/static/assets/style/favicon.ico')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

volunteers/urls.py
from django.urls import path

from . import views

app_name = "volunteers"
urlpatterns = [
    path("", views.home, name="home"),
    path("success", views.success, name="success"),
    path("signup", views.signup, name="signup"),
    path("volunteer_status_webhook", views.volunteer_status_webhook, name="volunteer_status_webhook"),
    path("<int:volunteer_id>", views.volunteer),
]

volunteers/models.py
from django.db import models

VOLUNTEER_ROLES = {
    "BOARDMEMBER": "board member",
    "COACH": "coach",
    "MANAGER": "manager",
    "SCOREKEEPER": "scorekeeper",
    "UMPIRE": "umpire",
}

class Volunteer(models.Model):
    first_name = models.CharField(max_length=30)
    middle_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email_address = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    background_check_status = models.CharField(max_length=20, default="pending")
    volunteer_role = models.CharField(max_length=12, choices=VOLUNTEER_ROLES, default="UMPIRE")
    order_id = models.IntegerField(blank=True, null=True)
    abuse_awareness_certificate = models.FileField(upload_to="tmp/certificates")

class VolunteerStatusMessage(models.Model):
    received_at = models.DateTimeField(auto_now_add=True, blank=True)
    class Meta:
        indexes = [
            models.Index(fields=["received_at"]),
        ]

volunteers/forms.py
from django.forms import ModelForm
from django import forms
from django_recaptcha.fields import ReCaptchaField 
from django_recaptcha.widgets import ReCaptchaV3
from .models import VOLUNTEER_ROLES, Volunteer

class SignupForm(ModelForm):
    first_name = forms.TextInput()
    middle_name = forms.TextInput()
    last_name = forms.TextInput()
    email_address = forms.TextInput()
    volunteer_role = forms.CharField(
        max_length=12,
        widget=forms.Select(choices=VOLUNTEER_ROLES),
        initial='UMPIRE',
    )
    abuse_awareness_certificate = forms.FileField()
    captcha = ReCaptchaField(widget=ReCaptchaV3(
        action='signup'
    ))
    
    class Meta:
        model = Volunteer
        fields = ['first_name', 'middle_name', 'last_name', 'email_address', 'volunteer_role', 'abuse_awareness_certificate']

volunteers/views.py
import datetime as dt
import os
import requests
from xml.etree import ElementTree

from random import randrange

from django.db.transaction import atomic, non_atomic_requests

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from django.shortcuts import get_object_or_404, render, redirect

from django.core.mail import send_mail

from django.http import HttpResponse

from django.utils import timezone

from .forms import SignupForm
from .models import Volunteer, VolunteerStatusMessage
from rrll.settings import (
    BASE_DIR,
    BACKGROUND_CHECK_PASSWORD,
    BACKGROUND_CHECK_USERNAME,
    BACKGROUND_CHECK_URL,
    DEVELOPMENT_MODE,
    EMAIL_HOST_USER,
    SEND_TO_JDP,
)


def home(request):
    return render(
        request,
        "volunteers/home.html",
        {"volunteer_list": Volunteer.objects.order_by("-created_at")},
    )


def success(request):
    return render(request, "volunteers/success.html", {})


def volunteer(request, volunteer_id):
    volunteer = get_object_or_404(Volunteer, pk=volunteer_id)
    if volunteer is not None:
        return render(request, "volunteers/volunteer.html", {"volunteer": volunteer})


@non_atomic_requests
def signup(request):
    error_messages = []
    if request.POST:
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            saved_volunteer = form.save()
            subject = "RRLL Volunteer Signup Successful"
            message = (
                request.POST["first_name"]
                + ", thank you for volunteering! You will receive an email from JDP shortly. Check the volunteers page for volunteer status."
            )
            if not DEVELOPMENT_MODE:
                send_mail(
                    subject,
                    message,
                    EMAIL_HOST_USER,
                    [request.POST["email_address"], EMAIL_HOST_USER],
                    True,
                )
            process_signup_payload(saved_volunteer.id)
            return redirect("volunteers:success")
        else:
            form = SignupForm()
            error_messages.append("Invalid captcha entry, please try again.")
    return render(
        request,
        "volunteers/signup.html",
        {"form": SignupForm, "error_messages": error_messages},
    )


@csrf_exempt
@require_POST
@non_atomic_requests
def volunteer_status_webhook(request):
    # TODO Do I need to give them a token? do they require it?
    """
    provided_token = request.headers.get("Jdp-Webhook-Token", "")
    if not compare_digest(provided_token, settings.JDP_WEBHOOK_TOKEN):
        return HttpResponseForbidden(
            "Incorrect token in Jdp-Webhook-Token header.",
            content_type="text/plain",
        )
    """
    VolunteerStatusMessage.objects.filter(
        received_at__lte=timezone.now() - dt.timedelta(days=7)
    ).delete()
    payload = ElementTree.fromstring(request.body)
    VolunteerStatusMessage.objects.create()
    process_webhook_payload(payload)
    return HttpResponse(status=204)


@atomic
def process_webhook_payload(payload):
    order_id = payload.find(".//OrderId")
    order_status = payload.find(".//OrderStatus")
    order_status_flag = order_status.get("flag")
    volunteer_set = Volunteer.objects.filter(order_id=int(order_id.text)).order_by(
        "-created_at"
    )
    if volunteer_set.exists() and "ready" in order_status.text:
        volunteer = volunteer_set.last()
        if order_status_flag.lower() == "true":
            volunteer.background_check_status = "inactive"
        else:
            volunteer.background_check_status = "active"
        volunteer.save()


@atomic
def process_signup_payload(id):
    # TODO may need to set and parse reference id
    if SEND_TO_JDP:
        volunteer = Volunteer.objects.get(id=id)

        order_template_tree = ElementTree.parse(
            os.path.join(BASE_DIR, "rrll/static/assets/digitalforms/order.xml")
        )

        given_name = order_template_tree.find(".//GivenName")
        given_name_orig = given_name.text
        middle_name = order_template_tree.find(".//MiddleName")
        middle_name_orig = middle_name.text
        family_name = order_template_tree.find(".//FamilyName")
        family_name_orig = family_name.text
        email_address = order_template_tree.find(".//EmailAddress")
        email_address_orig = email_address.text

        background_check_root = order_template_tree.getroot()
        original_user_id = background_check_root.get("userId")
        original_password = background_check_root.get("password")

        given_name.text = volunteer.first_name
        middle_name.text = volunteer.middle_name
        family_name.text = volunteer.last_name
        email_address.text = volunteer.email_address
        background_check_root.set("userId", BACKGROUND_CHECK_USERNAME)
        background_check_root.set("password", BACKGROUND_CHECK_PASSWORD)

        headers = {"Content-Type": "application/xml"}  # verify this
        # get post URL from settings
        response = requests.post(
            BACKGROUND_CHECK_URL,
            data=ElementTree.tostring(order_template_tree.getroot()),
            headers=headers,
        )

        # restore orignal values
        given_name.text = given_name_orig
        middle_name.text = middle_name_orig
        family_name.text = family_name_orig
        email_address.text = email_address_orig
        background_check_root.set("userId", original_user_id)
        background_check_root.set("password", original_password)

        if response.ok:
            if not DEVELOPMENT_MODE:
                # assuming order_id is in response
                order_id = response.text.find(".//OrderId")
                volunteer.order_id = int(order_id.text)
            else:
                volunteer.order_id = randrange(1000000)
            volunteer.save()
        else:
            print("Request Error ", response.status_code)

volunteers/templates/volunteers/home.html
{% extends "base_template.html" %}

{% block title %}Home{% endblock %}
{% block header_title %}Volunteers{% endblock %}
{% block header_content %}{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'assets/style/dataTables.bootstrap5.css' %}">
<link rel="stylesheet" href="{% static 'assets/style/dataTables.bootstrap.min.css' %}">
<script src="../static/assets/js/jquery-3.7.1.js"></script>
<script src="../static/assets/js/dataTables.js"></script>
<script src="../static/assets/js/dataTables.bootstrap5.js"></script>
<script>
    $(document).ready(function () {
        new DataTable('#volunteers', {
            order: [[3, 'desc']]
        });
    });
</script>
<div>
    <a href="{% url 'volunteers:signup' %}" class="w-20 btn btn-danger" role="button">Signup</a>
</div>
<div>
    <table id="volunteers" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Role</th>
                <th scope="col">Submitted</th>
                <th scope="col">Status</th>
                <th scope="col">Abuse Awareness Certificate</th>
            </tr>
        </thead>
        <tbody>
            {% for volunteer in volunteer_list %}
            <tr>
                <td>{{volunteer.first_name}}</td>
                <td>{{volunteer.last_name}}</td>
                <td>{{volunteer.volunteer_role}}</td>
                <td>{{volunteer.created_at}}</td>
                {% if volunteer.background_check_status == "pending" %}
                <td style="background-color: rgba(255, 255, 0, 0.6) !important;color: black">{{volunteer.background_check_status}}</td>
                {% elif volunteer.background_check_status == "inactive" %}
                <td style="background-color: rgba(255, 51, 51, 0.6) !important;">{{volunteer.background_check_status}}</td>
                {% else %}
                <td style="background-color: rgba(45, 179, 0, 0.6) !important;">{{volunteer.background_check_status}}</td>
                {% endif %}
                <td><a href="{{ volunteer.abuse_awareness_certificate.url }}">{{volunteer.abuse_awareness_certificate.name}}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div>
    <a href="{% url 'volunteers:signup' %}" class="w-20 btn btn-danger" role="button">Signup</a>
</div>
{% endblock %}

volunteers/templates/volunteers/signup.html
{% extends "base_template.html" %}

{% block title %}Volunteer Signup{% endblock %}
{% block header_title %}Volunteer Signup{% endblock %}
{% block header_content %}{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
{% if error_messages|length > 0 %}
    <p>Please address the follow errors and re-submit</p>
    <ul>
    {% for message in error_messages %}
        <li>{{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}    
<form id="signup-form" method="POST" action="{% url 'volunteers:signup' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-danger">Submit</button>
</form>
<a href="{% url 'volunteers:home' %}">All Volunteers</a>
{% endblock %}

volunteers/templates/volunteers/success.html
{% extends "base_template.html" %}

{% block title %}Volunteer Details{% endblock %}
{% block header_title %}{% endblock %}
{% block header_content %}{% endblock %}
{% block content %}
<h2>Successfully submitted volunteer form!</h2>
<a href="{% url 'volunteers:home' %}"">All Volunteers</a>
{% endblock %}

volunteers/templates/volunteers/volunteer.html
{% extends "base_template.html" %}

{% block header_title %}Volunteer Details{% endblock %}
{% block header_content %}{% endblock %}
{% block content %}
<p>First Name: {{volunteer.first_name}}</p>
<p>Last Name:  {{volunteer.last_name}}</p>
<p>Submitted:  {{volunteer.created_at}}</p>
<p>Status:     {{volunteer.background_check_status}}</p>
<p><a href="{{ volunteer.abuse_awareness_certificate.url }}">{{ volunteer.abuse_awareness_certificate.name }}</a></p>
<p><a href="{% url 'volunteers:home' %}" >All Volunteers</a></p>
{% endblock %}