boardmembers/urls.py
from django.urls import path

from . import views

app_name = "boardmembers"
urlpatterns = [
    path("", views.index, name="index"),
]

rrll/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView
from django.urls import include, path, re_path

# from rrll import settings

from . import views

urlpatterns = [
    path("volunteers/", include("volunteers.urls")),
    path("boardmembers/", include("boardmembers.urls")),
    path("", views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("schedule/", views.schedule, name="schedule"),
    path("safety/", views.safety, name="safety"),
    path("news/", views.news, name="news"),
    path("registration/", views.registration, name="registration"),
    path('admin/', admin.site.urls),
    re_path(r'^favicon\.ico$',RedirectView.as_view(url='/static/assets/style/favicon.ico')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

volunteers/urls.py
from django.urls import path

from . import views

app_name = "volunteers"
urlpatterns = [
    path("", views.home, name="home"),
    path("success", views.success, name="success"),
    path("signup", views.signup, name="signup"),
    path("volunteer_status_webhook", views.volunteer_status_webhook, name="volunteer_status_webhook"),
    path("<int:volunteer_id>", views.volunteer),
]

rrll/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect


def index(request):
    return render(request, 'index.html', {}) 

def contact(request):
    return HttpResponse("You're at rrll contact.")

def schedule(request):
    return render(request, 'schedule.html', {}) 

def safety(request):
    return render(request, 'safety.html', {})

def news(request):
    return render(request, 'news.html', {})

def registration(request):
    return render(request, 'registration.html', {})

rrll/templates/base_template.html
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'assets/style/bootstrap.min.css' %}">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">

    <title>{% block title %}Roadrunner Little League{% endblock %}</title>

    <script src="../static/assets/js/popper.min.js"></script>
    <script src="../static/assets/js/bootstrap.bundle.min.js"></script>
    <script src="../static/assets/js/color-modes.js"></script>

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
            display: block !important;
        }

        body {
            background-image: linear-gradient(180deg, var(--bs-secondary-bg), var(--bs-body-bg) 100px, var(--bs-body-bg));
        }

        .container {
            max-width: 960px;
        }

        .pricing-header {
            max-width: 700px;
        }
    </style>

    <!-- Custom styles for this template -->
</head>

<body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check2" viewBox="0 0 16 16">
            <path
                d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
        </symbol>
        <symbol id="circle-half" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
        </symbol>
        <symbol id="moon-stars-fill" viewBox="0 0 16 16">
            <path
                d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
            <path
                d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
        </symbol>
        <symbol id="sun-fill" viewBox="0 0 16 16">
            <path
                d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
        </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
        <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
            <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
                <use href="#circle-half"></use>
            </svg>
            <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
        </button>
        <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                    <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                        <use href="#sun-fill"></use>
                    </svg>
                    Light
                    <svg class="bi ms-auto d-none" width="1em" height="1em">
                        <use href="#check2"></use>
                    </svg>
                </button>
            </li>
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                    <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                        <use href="#moon-stars-fill"></use>
                    </svg>
                    Dark
                    <svg class="bi ms-auto d-none" width="1em" height="1em">
                        <use href="#check2"></use>
                    </svg>
                </button>
            </li>
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                    <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                        <use href="#circle-half"></use>
                    </svg>
                    Auto
                    <svg class="bi ms-auto d-none" width="1em" height="1em">
                        <use href="#check2"></use>
                    </svg>
                </button>
            </li>
        </ul>
    </div>


    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check" viewBox="0 0 16 16">
            <title>Check</title>
            <path
                d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
        </symbol>
    </svg>

    <div class="container py-3">
        <header>
            <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
                <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
                    <!-- <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg> -->
                    <img class="mb-2" src="../static/assets/style/header-logo.png" height="96px" alt="">
                </a>

                <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none"
                        href="{% url 'boardmembers:index' %}">Board</a>
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'news' %}">News</a>
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'registration' %}">Registration</a>
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'safety' %}">Safety</a>
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none"
                        href="{% url 'schedule' %}">Schedule</a>
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none"
                        href="{% url 'volunteers:home' %}">Volunteer</a>
                </nav>
            </div>

            <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
                <h1 class="display-4 fw-normal text-body-emphasis">{% block header_title %}Header Here{% endblock %}
                </h1>
                <p class="fs-5 text-body-secondary">{% block header_content %}Quickly build an effective pricing table
                    for your potential customers with this Bootstrap example. It’s built with default Bootstrap
                    components and utilities with little customization.{% endblock %}</p>
            </div>
        </header>

        <main>
            {% block content %}{% endblock %}
        </main>

        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    <img class="mb-2" src="../static/assets/style/footer-icon-small.png" alt="" width="24" height="19">
                    <small class="d-block mb-3 text-body-secondary">&copy; 2024</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Resources</h5>
                    <ul class="list-unstyled text-small">
                        <li class="mb-1"><a class="link-secondary text-decoration-none" href="{% url 'news' %}">News</a></li>
                        <li class="mb-1"><a class="link-secondary text-decoration-none"
                                href="{% url 'safety' %}">Safety</a></li>
                        <li class="mb-1"><a class="link-secondary text-decoration-none"
                                href="{% url 'schedule' %}">Schedule</a></li>
                        <li class="mb-1"><a class="link-secondary text-decoration-none"
                                href="{% url 'volunteers:home' %}">Volunteer</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Contact Us</h5>
                    <div class="text-small text-body-secondary">
                        Roadrunner Little League<br>
                        P.O. Box 16115<br>
                        Albuquerque, NM 87191-1615<br>
                        Phone: (505) 299-9702<br>
                        Email: info@rrll.org<br>
                    </div>
                </div>
                <div class="col-6 col-md">
                    <div style="padding: 5px;">
                        <a href="https://login.stacksports.com/login?client_id=612b0399b1854a002e427f78&redirect_uri=https://core-api.bluesombrero.com/login/redirect/portal/50346&app_name=Roadrunner+Little+League&portalid=50346&instancekey=clubs" role="button" class="btn btn-secondary">Register Here</a>
                    </div>
                    <div style="padding: 5px;">
                        <a href="https://www.facebook.com/RoadrunnerLittleLeagueAlbuquerqueNM/" role="button" class="btn btn-secondary">Follow us on Facebook</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</body>

</html>

rrll/templates/index.html
{% extends "base_template.html" %}

{% block title %}Roadrunner Little League{% endblock %}

{% block header_title %}Roadrunner Little League{% endblock %}
{% block header_content %}
T-Ball through Junior Divisions available. Register today!
{% endblock %}

{%block content %}
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v18.0"
    nonce="uKTPGjNf"></script>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-danger">
            <div class="card-header py-3 border-danger">
                <h4 class="my-0 fw-normal">
                    <svg fill="#000000" height="100%" width="100%" version="1.1" id="Capa_1"
                        xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                        viewBox="0 0 297 297" xml:space="preserve">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier">
                            <path
                                d="M47.156,188.376c0,2.861,1.109,14.855,9.212,29.09c6.86,12.052,19.88,26.147,43.843,29.262v40.243 c0,5.538,4.49,10.029,10.029,10.029c5.538,0,10.028-4.491,10.028-10.029v-49.644c0-5.538-4.49-10.029-10.028-10.029 c-16.487,0-28.643-6.465-36.128-19.216c-5.521-9.402-6.922-17.345-6.922-20.844c0-21.168,0-82.294,0-82.294 c0-1.782,0-6.519,8.237-6.519c8.235,0,8.235,4.736,8.235,6.519v34.548c0,2.736,1.117,5.354,3.095,7.246 c1.977,1.891,4.639,2.905,7.374,2.773c0.024-0.011,5.862,0.022,13.244,4.191c11.333,6.402,20.478,19.249,26.445,37.151 c1.752,5.255,7.432,8.097,12.686,6.344c5.255-1.752,8.095-7.432,6.343-12.686c-12.976-38.932-35.79-50.37-49.128-53.701V38.037 c0-2.17,0-5.803,8.236-5.803c8.235,0,8.235,3.633,8.235,5.803v54.73c0,5.539,4.491,10.029,10.029,10.029s10.028-4.49,10.028-10.029 V25.86c0-2.17,0-5.803,8.236-5.803c8.235,0,8.235,3.633,8.235,5.803v66.907c0,5.539,4.491,10.029,10.029,10.029 s10.029-4.49,10.029-10.029v-54.73c0-2.17,0-5.803,8.235-5.803c8.236,0,8.236,3.633,8.236,5.803v71.278 c0,5.538,4.491,10.029,10.029,10.029c5.539,0,10.029-4.491,10.029-10.029V71.849c0-1.782,0-6.519,8.236-6.519 c8.236,0,8.244,4.736,8.244,6.519v116.402c0.011,0.177,0.717,18.087-9.919,29.341c-6.086,6.441-15.135,9.706-26.894,9.706 c-5.539,0-10.029,4.491-10.029,10.029v49.644c0,5.538,4.49,10.029,10.029,10.029c5.538,0,10.028-4.491,10.028-10.029v-40.253 c12.868-1.712,23.415-6.855,31.443-15.35c15.825-16.745,15.516-40.586,15.391-43.899V71.849c0-15.647-11.636-26.577-28.294-26.577 c-2.912,0-5.667,0.342-8.236,0.977v-8.211c0-15.469-11.371-25.86-28.295-25.86c-3.986,0-7.66,0.583-10.954,1.667 C169.732,5.253,160.514,0,148.487,0c-12.028,0-21.245,5.253-25.575,13.844c-3.294-1.084-6.968-1.667-10.954-1.667 c-16.924,0-28.295,10.392-28.295,25.86v41.307c-2.569-0.635-5.324-0.976-8.235-0.976c-16.66,0-28.295,10.93-28.295,26.577 C47.132,104.944,47.156,166.737,47.156,188.376z">
                            </path>
                        </g>
                    </svg>
                </h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">Volunteer</h1>
                <div class="mt-3 mb-4">
                    Volunteers are the lifeblood of Little League! Every aspect of Little League is dependent upon the
                    work of dedicated volunteers, and every person helping makes an enormous difference!
                </div>
                <a href="{% url 'volunteers:home' %}" role="button" class="w-100 btn btn-lg btn-danger">Learn More</a>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">
                    <svg fill="#000000" viewBox="0 0 16 16" id="register-16px" xmlns="http://www.w3.org/2000/svg">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier">
                            <path id="Path_184" data-name="Path 184"
                                d="M57.5,41a.5.5,0,0,0-.5.5V43H47V31h2v.5a.5.5,0,0,0,.5.5h5a.5.5,0,0,0,.5-.5V31h2v.5a.5.5,0,0,0,1,0v-1a.5.5,0,0,0-.5-.5H55v-.5A1.5,1.5,0,0,0,53.5,28h-3A1.5,1.5,0,0,0,49,29.5V30H46.5a.5.5,0,0,0-.5.5v13a.5.5,0,0,0,.5.5h11a.5.5,0,0,0,.5-.5v-2A.5.5,0,0,0,57.5,41ZM50,29.5a.5.5,0,0,1,.5-.5h3a.5.5,0,0,1,.5.5V31H50Zm11.854,4.646-2-2a.5.5,0,0,0-.708,0l-6,6A.5.5,0,0,0,53,38.5v2a.5.5,0,0,0,.5.5h2a.5.5,0,0,0,.354-.146l6-6A.5.5,0,0,0,61.854,34.146ZM54,40V38.707l5.5-5.5L60.793,34.5l-5.5,5.5Zm-2,.5a.5.5,0,0,1-.5.5h-2a.5.5,0,0,1,0-1h2A.5.5,0,0,1,52,40.5Zm0-3a.5.5,0,0,1-.5.5h-2a.5.5,0,0,1,0-1h2A.5.5,0,0,1,52,37.5ZM54.5,35h-5a.5.5,0,0,1,0-1h5a.5.5,0,0,1,0,1Z"
                                transform="translate(-46 -28)"></path>
                        </g>
                    </svg>
                </h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">Registration
                </h1>
                <div class="mt-3 mb-4">
                    Roadrunner is pleased to announce 2024 registration. We will be offering T-Ball (beginning at age 4)
                    and baseball programs.
                </div>
                <a href="{% url 'registration' %}" role="button" class="w-100 btn btn-lg btn-outline-danger">Learn More</a>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">
                    <svg viewBox="0 0 24 24" id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg"
                        fill="#000000">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier">
                            <defs>
                                <style>
                                    .cls-1 {
                                        fill: none;
                                        stroke: #020202;
                                        stroke-miterlimit: 10;
                                        stroke-width: 1.91px;
                                    }
                                </style>
                            </defs>
                            <path class="cls-1"
                                d="M21.55,8.18V22.5H14.86A2.86,2.86,0,0,1,12,19.64h0A2.86,2.86,0,0,1,9.14,22.5H2.45V8.18A2.86,2.86,0,0,0,5.32,5.32V1.5H18.68V5.32A2.86,2.86,0,0,0,21.55,8.18Z">
                            </path>
                            <polygon class="cls-1" points="12 10.09 8.18 1.5 15.82 1.5 12 10.09"></polygon>
                            <line class="cls-1" x1="12" y1="19.64" x2="12" y2="10.09"></line>
                            <line class="cls-1" x1="2.45" y1="12.95" x2="9.14" y2="12.95"></line>
                            <line class="cls-1" x1="2.45" y1="17.73" x2="9.14" y2="17.73"></line>
                            <line class="cls-1" x1="14.86" y1="12.95" x2="21.55" y2="12.95"></line>
                            <line class="cls-1" x1="14.86" y1="17.73" x2="21.55" y2="17.73"></line>
                        </g>
                    </svg>
                </h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">Safety
                </h1>
                <div class="mt-3 mb-4">
                    Access safety resources including the recorded safety clinic and accident tracking form.
                </div>
                <a href="{% url 'safety' %}" role="button" class="w-100 btn btn-lg btn-outline-danger">Learn More</a>
            </div>
        </div>
    </div>
</div>
<div style="display: block;margin-left: auto;margin-right: auto;width: 50%;">
    <h2 style="padding-bottom: 20px;text-align: center;" class="card-title pricing-card-title">Roadrunner Facebook Feed
    </h2>
    <div class="fb-page" data-href="https://www.facebook.com/RoadrunnerLittleLeagueAlbuquerqueNM"
        data-tabs="timeline,events" data-width="500" data-height="" data-small-header="false"
        data-adapt-container-width="true" data-hide-cover="true" data-show-facepile="false">
        <blockquote cite="https://www.facebook.com/RoadrunnerLittleLeagueAlbuquerqueNM" class="fb-xfbml-parse-ignore">
            <a href="https://www.facebook.com/RoadrunnerLittleLeagueAlbuquerqueNM"> RRLL Facebook Feed</a>
        </blockquote>
    </div>
</div>
{% endblock %}

rrll/templates/news.html
{% extends "base_template.html" %}

{% block title %}News{% endblock %}

{% block header_title %}{% endblock %}
{% block header_content %}{% endblock %}

{% block content %}
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v18.0"
    nonce="uKTPGjNf"></script>
<div style="display: block;margin-left: auto;margin-right: auto;width: 50%;">
    <h2 style="padding-bottom: 20px;text-align: center;" class="card-title pricing-card-title">Roadrunner Facebook Feed
    </h2>
    <div class="fb-page" data-href="https://www.facebook.com/RoadrunnerLittleLeagueAlbuquerqueNM"
        data-tabs="timeline,events" data-width="500" data-height="" data-small-header="false"
        data-adapt-container-width="true" data-hide-cover="true" data-show-facepile="false">
        <blockquote cite="https://www.facebook.com/RoadrunnerLittleLeagueAlbuquerqueNM" class="fb-xfbml-parse-ignore">
            <a href="https://www.facebook.com/RoadrunnerLittleLeagueAlbuquerqueNM"> RRLL Facebook Feed</a>
        </blockquote>
    </div>
</div>
{% endblock %}